### ISSUE TITLE
scATAC-seq data source

### ISSUE THREAD

**Issue by BoxWong** [Yijia-Jiang/scATAnno-main#1]
Hi Yijia,

Thank you for developing this tool and I already started testing this out. Hopefully will have results soon :)

I do have a question though and a just precaution: I might be asking just a remotely related question. In the paper that you put on biorxiv, you mentioned that you downloaded raw fastq data from BioProject (PRJNA532774). I was also trying to use the same dataset, but I found that the raw data on GEO only has two biological reads without any technical reads indicating corresponding cell barcode information. So I'm just wondering how you got the cell barcode and did the preprocess (e.g. mapping)? 

Best,
Xin

**Comment by Yijia-Jiang** [comment]
Hi Xin, you may find cell barcodes from their original paper: https://pubmed.ncbi.nlm.nih.gov/31375813/, and raw data from GSE129785.

We preprocessed the data using cellranger-atac software to generate fragment files. Hope that helps.

**Comment by BoxWong** [comment]
Hi Yijia,

Thanks for the reply. I am still a bit confused though :( Since normally when you check the scRNA/scATAC-seq data on GEO, each spot would have at least three reads. In the case of scATAC-seq, read1N, read2N and cell barcode (16 bp) are always present. GSE129785 does not seem to include the cell barcode info.
I also found the cell barcodes listed in their original paper (as you also told in your reply), but they should just be served as a whitelist for the curation of cell barcodes, right? For a cellranger-atac run, you probably also need a sequenced cell barcode file which I could not find yet. Could you please let me know where you find that file?

Thanks in advance :)

Best,
Xin

发件人: Yijia (Alva) Jiang ***@***.***>
发送时间: 2023年7月6日 0:39
收件人: Yijia-Jiang/scATAnno-main ***@***.***>
抄送: Wang, Xin ***@***.***>; Author ***@***.***>
主题: Re: [Yijia-Jiang/scATAnno-main] scATAC-seq data source (Issue #1)


Hi Xin, you may find cell barcodes from their original paper: https://pubmed.ncbi.nlm.nih.gov/31375813/, and raw data from GSE129785.

We preprocessed the data using cellranger-atac software to generate fragment files. Hope that helps.

―

**Comment by BoxWong** [comment]
Hi Yijia,

Thanks for the reply. I am still a bit confused though :( Since normally when you check the scRNA/scATAC-seq data on GEO, each spot would have at least three reads. In the case of scATAC-seq, read1N, read2N and cell barcode (16 bp) are always present. GSE129785 does not seem to include the cell barcode info. 
I also found the cell barcodes listed in their original paper (as you also told in your reply), but they should just be served as a whitelist for the curation of cell barcodes, right? For a cellranger-atac run, you probably also need a sequenced cell barcode file which I could not find yet. Could you please let me know where you find that file?

Thanks in advance :)

Best,
Xin

**Comment by Yijia-Jiang** [comment]
The cell barcode info should be stored as something like GSE129785_scATAC-Hematopoiesis-All.cell_barcodes.txt.gz in GSE129785. We downloaded the data from https://www.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA532774&o=acc_s%3Aa. Feel free to let me know if you have further questions.
